### ISSUE TITLE
File path parse bug.

### ISSUE THREAD

**Issue by haphamTars** [yuweisunn/segmented-FL#1]
when i run code, i got a trouble when enter TypeA as anomaly type in code scenario, maybe it is about file path parse. Can you check it out. i attached image here.
![bug_FL_Segment](https://user-images.githubusercontent.com/82306104/175814805-c363d7bf-027c-478d-883e-ea309cf66866.png)

**Comment by yuweisunn** [comment]
As attached, the file path is fine. Can you try to print the os.path.split(fpath)[0].split("/") to see if the index 4 exists. Otherwise, 1) check the correct location of your dataset or 2) change the path. Thank you.
![Screen_Capture_-_Jun_27__8_24_AM](https://user-images.githubusercontent.com/60568855/175837894-2dd64ac1-c6e6-4e7d-a01d-adb9c8774252.png)
